# Generated by Django 5.2.4 on 2025-08-06 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='message',
            new_name='message_analysis',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='feedback_text',
        ),
        migrations.AddField(
            model_name='feedback',
            name='additional_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='was_correct',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
