# Generated by Django 5.2.3 on 2025-06-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securanet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suspicioussite',
            old_name='created_at',
            new_name='flagged_at',
        ),
        migrations.AddField(
            model_name='suspicioussite',
            name='detection_method',
            field=models.CharField(choices=[('html', 'HTML Structure'), ('screenshot', 'Visual Screenshot'), ('domain', 'Domain Reputation')], default='html', max_length=50),
        ),
        migrations.AddField(
            model_name='suspicioussite',
            name='screenshot_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
