# Generated by Django 5.2.4 on 2025-07-15 06:36

import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securanet', '0002_rename_created_at_suspicioussite_flagged_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('domain', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('reason', models.TextField(blank=True, null=True)),
                ('method', models.CharField(blank=True, max_length=50, null=True)),
                ('reputation', models.CharField(blank=True, max_length=100, null=True)),
                ('google_safebrowsing', jsonfield.fields.JSONField(blank=True, null=True)),
                ('virustotal', jsonfield.fields.JSONField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('screenshot', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='suspicioussite',
            name='detection_method',
            field=models.CharField(choices=[('html', 'HTML Structure'), ('screenshot', 'Visual Screenshot'), ('domain', 'Domain Reputation'), ('google_safebrowsing', 'Google Safe Browsing'), ('virustotal', 'VirusTotal')], default='html', max_length=50),
        ),
    ]
