# Generated by Django 5.1.4 on 2025-07-14 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_filechangelog_options_and_more'),
        ('myapp', '0005_auto_20250714_1050'),
    ]

    operations = [
    ]
