# Generated by Django 5.2.3 on 2025-07-16 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_merge_20250714_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.TextField()),
                ('content_hash', models.CharField(max_length=64)),
                ('risk_score', models.FloatField()),
                ('risk_level', models.CharField(max_length=20)),
                ('analysis_result', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='filechangelog',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='filechangelog',
            name='myapp_filec_risk_le_bc7e82_idx',
        ),
        migrations.RemoveIndex(
            model_name='filechangelog',
            name='myapp_filec_change__6c817d_idx',
        ),
        migrations.RemoveField(
            model_name='filechangelog',
            name='ai_analysis',
        ),
        migrations.RemoveField(
            model_name='filechangelog',
            name='analyzed',
        ),
        migrations.RemoveField(
            model_name='filechangelog',
            name='dedup_key',
        ),
        migrations.RemoveField(
            model_name='filechangelog',
            name='file_extension',
        ),
        migrations.RemoveField(
            model_name='filechangelog',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='filechangelog',
            name='recommendation',
        ),
        migrations.RemoveField(
            model_name='filechangelog',
            name='risk_level',
        ),
        migrations.AddField(
            model_name='filechangelog',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='filechangelog',
            name='change_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AddIndex(
            model_name='fileanalysis',
            index=models.Index(fields=['file_path'], name='myapp_filea_file_pa_42e4da_idx'),
        ),
        migrations.AddIndex(
            model_name='fileanalysis',
            index=models.Index(fields=['risk_level'], name='myapp_filea_risk_le_3f47da_idx'),
        ),
        migrations.AddIndex(
            model_name='fileanalysis',
            index=models.Index(fields=['created_at'], name='myapp_filea_created_99e2df_idx'),
        ),
        migrations.AddField(
            model_name='filechangelog',
            name='analysis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.fileanalysis'),
        ),
        migrations.AddIndex(
            model_name='filechangelog',
            index=models.Index(fields=['file_path', 'timestamp'], name='myapp_filec_file_pa_7b77e3_idx'),
        ),
        migrations.AddIndex(
            model_name='filechangelog',
            index=models.Index(fields=['change_type'], name='myapp_filec_change__9469c9_idx'),
        ),
    ]
