# Generated by Django 5.2.3 on 2025-08-03 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_filechangelog_dedup_key_filechangelog_recommendation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileanalysis',
            options={'verbose_name_plural': 'File Analyses'},
        ),
        migrations.AlterModelOptions(
            name='filechangelog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveIndex(
            model_name='filechangelog',
            name='myapp_filec_file_pa_7b77e3_idx',
        ),
        migrations.RemoveField(
            model_name='filechangelog',
            name='dedup_key',
        ),
        migrations.RemoveField(
            model_name='filechangelog',
            name='metadata',
        ),
        migrations.AlterField(
            model_name='fileanalysis',
            name='analysis_result',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='fileanalysis',
            name='content_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='fileanalysis',
            name='file_path',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='fileanalysis',
            name='risk_level',
            field=models.CharField(default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='fileanalysis',
            name='risk_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='filechangelog',
            name='analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.fileanalysis'),
        ),
        migrations.AlterField(
            model_name='filechangelog',
            name='change_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='filechangelog',
            name='file_path',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='filechangelog',
            name='risk_level',
            field=models.CharField(default='unknown', max_length=20),
        ),
        migrations.AddIndex(
            model_name='fileanalysis',
            index=models.Index(fields=['content_hash'], name='myapp_filea_content_d62f72_idx'),
        ),
        migrations.AddIndex(
            model_name='filechangelog',
            index=models.Index(fields=['file_path'], name='myapp_filec_file_pa_50ec76_idx'),
        ),
        migrations.AddIndex(
            model_name='filechangelog',
            index=models.Index(fields=['timestamp'], name='myapp_filec_timesta_63d45e_idx'),
        ),
    ]
