# Generated by Django 5.2.3 on 2025-08-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_fileanalysis_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filechangelog',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='filechangelog',
            name='myapp_filec_change__9469c9_idx',
        ),
        migrations.RemoveIndex(
            model_name='filechangelog',
            name='myapp_filec_risk_le_d36b55_idx',
        ),
        migrations.RemoveIndex(
            model_name='filechangelog',
            name='myapp_filec_file_pa_50ec76_idx',
        ),
        migrations.RemoveIndex(
            model_name='filechangelog',
            name='myapp_filec_timesta_63d45e_idx',
        ),
        migrations.RemoveField(
            model_name='filechangelog',
            name='analysis',
        ),
        migrations.AlterField(
            model_name='filechangelog',
            name='file_path',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='filechangelog',
            name='risk_level',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='filechangelog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='filechangelog',
            index=models.Index(fields=['-timestamp'], name='myapp_filec_timesta_6197aa_idx'),
        ),
        migrations.AddIndex(
            model_name='filechangelog',
            index=models.Index(fields=['risk_level', '-timestamp'], name='myapp_filec_risk_le_05be8c_idx'),
        ),
    ]
