# Generated by Django 5.2.3 on 2025-07-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filechangelog',
            name='recommendation',
            field=models.TextField(blank=True, default='No action needed.'),
        ),
        migrations.AddField(
            model_name='filechangelog',
            name='risk_level',
            field=models.CharField(default='safe', max_length=20),
        ),
    ]
