# Generated by Django 5.2.3 on 2025-07-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0002_filechangelog_recommendation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filechangelog',
            name='suspicious',
        ),
        migrations.AddField(
            model_name='filechangelog',
            name='dedup_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='filechangelog',
            name='file_path',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='filechangelog',
            name='recommendation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
