# Generated by Django 5.1.4 on 2025-07-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0003_remove_filechangelog_suspicious_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filechangelog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='filechangelog',
            name='ai_analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='filechangelog',
            name='analyzed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='filechangelog',
            name='file_extension',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='filechangelog',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filechangelog',
            name='change_type',
            field=models.CharField(choices=[('created', 'Created'), ('modified', 'Modified'), ('deleted', 'Deleted'), ('moved', 'Moved')], max_length=20),
        ),
        migrations.AlterField(
            model_name='filechangelog',
            name='dedup_key',
            field=models.CharField(db_index=True, default='default_key', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='filechangelog',
            name='risk_level',
            field=models.CharField(choices=[('safe', 'Safe'), ('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical Risk')], default='safe', max_length=20),
        ),
        migrations.AddIndex(
            model_name='filechangelog',
            index=models.Index(fields=['risk_level', 'timestamp'], name='file_management_filec_risk_le_bc7e82_idx'),
        ),
        migrations.AddIndex(
            model_name='filechangelog',
            index=models.Index(fields=['change_type', 'timestamp'], name='file_management_filec_change__6c817d_idx'),
        ),
    ]
