# Generated by Django 5.2.4 on 2025-08-19 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0010_alter_filechangelog_options_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fileanalysis',
            new_name='file_manage_file_pa_2e9d28_idx',
            old_name='myapp_filea_file_pa_42e4da_idx',
        ),
        migrations.RenameIndex(
            model_name='fileanalysis',
            new_name='file_manage_risk_le_c41872_idx',
            old_name='myapp_filea_risk_le_3f47da_idx',
        ),
        migrations.RenameIndex(
            model_name='fileanalysis',
            new_name='file_manage_created_396b4d_idx',
            old_name='myapp_filea_created_99e2df_idx',
        ),
        migrations.RenameIndex(
            model_name='fileanalysis',
            new_name='file_manage_content_a553d7_idx',
            old_name='myapp_filea_content_d62f72_idx',
        ),
        migrations.RenameIndex(
            model_name='filechangelog',
            new_name='file_manage_timesta_b30dc8_idx',
            old_name='myapp_filec_timesta_6197aa_idx',
        ),
        migrations.RenameIndex(
            model_name='filechangelog',
            new_name='file_manage_risk_le_c476c9_idx',
            old_name='myapp_filec_risk_le_05be8c_idx',
        ),
    ]
