# Generated by Django 4.2.7 on 2025-08-05 13:44

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KnownSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(unique=True)),
                ("domain", models.CharField(max_length=255)),
                (
                    "screenshot",
                    models.ImageField(blank=True, null=True, upload_to="screenshots/"),
                ),
                (
                    "screenshot_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("html_signature", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ScanLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("domain", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=50)),
                ("reason", models.TextField(blank=True, null=True)),
                ("method", models.CharField(blank=True, max_length=50, null=True)),
                ("reputation", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "google_safebrowsing",
                    jsonfield.fields.JSONField(blank=True, null=True),
                ),
                ("virustotal", jsonfield.fields.JSONField(blank=True, null=True)),
                ("message", models.TextField(blank=True, null=True)),
                ("screenshot", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SuspiciousSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("domain", models.CharField(max_length=255)),
                (
                    "detection_method",
                    models.CharField(
                        choices=[
                            ("html", "HTML Structure"),
                            ("screenshot", "Visual Screenshot"),
                            ("domain", "Domain Reputation"),
                            ("google_safebrowsing", "Google Safe Browsing"),
                            ("virustotal", "VirusTotal"),
                        ],
                        default="html",
                        max_length=50,
                    ),
                ),
                ("is_flagged", models.BooleanField(default=False)),
                ("reason", models.TextField(blank=True, null=True)),
                (
                    "screenshot",
                    models.ImageField(blank=True, null=True, upload_to="screenshots/"),
                ),
                (
                    "screenshot_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("flagged_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
