# Generated by Django 4.2.7 on 2025-08-05 23:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FileChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("file_path", models.TextField()),
                ("change_type", models.CharField(max_length=20)),
                ("risk_level", models.CharField(db_index=True, max_length=20)),
                ("recommendation", models.TextField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="myapp_filec_timesta_6197aa_idx"
                    ),
                    models.Index(
                        fields=["risk_level", "-timestamp"],
                        name="myapp_filec_risk_le_05be8c_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FileAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_path", models.CharField(max_length=1024)),
                (
                    "content_hash",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("risk_score", models.FloatField(default=0.0)),
                ("risk_level", models.CharField(default="unknown", max_length=20)),
                ("analysis_result", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "File Analyses",
                "indexes": [
                    models.Index(
                        fields=["file_path"], name="myapp_filea_file_pa_42e4da_idx"
                    ),
                    models.Index(
                        fields=["risk_level"], name="myapp_filea_risk_le_3f47da_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="myapp_filea_created_99e2df_idx"
                    ),
                    models.Index(
                        fields=["content_hash"], name="myapp_filea_content_d62f72_idx"
                    ),
                ],
            },
        ),
    ]
