# Generated by Django 5.2.3 on 2025-07-16 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_fileanalysis_alter_filechangelog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filechangelog',
            name='dedup_key',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='filechangelog',
            name='recommendation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filechangelog',
            name='risk_level',
            field=models.CharField(choices=[('safe', 'Safe'), ('suspicious', 'Suspicious'), ('dangerous', 'Dangerous')], default='safe', max_length=20),
        ),
        migrations.AlterField(
            model_name='filechangelog',
            name='analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.fileanalysis'),
        ),
        migrations.AlterField(
            model_name='filechangelog',
            name='change_type',
            field=models.CharField(choices=[('created', 'Created'), ('modified', 'Modified'), ('deleted', 'Deleted'), ('renamed', 'Renamed')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='filechangelog',
            index=models.Index(fields=['risk_level'], name='myapp_filec_risk_le_d36b55_idx'),
        ),
    ]
