# Generated by Django 4.2.7 on 2025-08-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0010_alter_filechangelog_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="filechangelog",
            name="dedup_key",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
    ]
